cat-home/src/main/java/com/dianping/cat/report/page/model/Payload.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.report.page.model;

import java.util.Arrays;

import org.unidal.web.mvc.ActionContext;
import org.unidal.web.mvc.ActionPayload;
import org.unidal.web.mvc.payload.annotation.FieldMeta;
import org.unidal.web.mvc.payload.annotation.PathMeta;

import com.dianping.cat.mvc.ApiPayload;
import com.dianping.cat.report.ReportPage;
import com.dianping.cat.report.service.ModelPeriod;

public class Payload extends ApiPayload implements ActionPayload<ReportPage, Action> {
	@FieldMeta("op")
	private Action m_action;

	private ReportPage m_page;

	@PathMeta("path")
	private String[] m_path;

	@Override
	public Action getAction() {
		return m_action;
	}

	public void setAction(String action) {
		m_action = Action.getByName(action, Action.XML);
	}

	public String getDomain() {
		if (m_path.length > 1) {
			return m_path[1];
		} else {
			return null;
		}
	}

	@Override
	public ReportPage getPage() {
		return m_page;
	}

	@Override
	public void setPage(String page) {
		m_page = ReportPage.getByName(page, ReportPage.MODEL);
	}

	public ModelPeriod getPeriod() {
		if (m_path.length > 2) {
			return ModelPeriod.getByName(m_path[2], ModelPeriod.CURRENT);
		} else {
			return ModelPeriod.CURRENT;
		}
	}

	public String getReport() {
		if (m_path.length > 0) {
			return m_path[0];
		} else {
			return null;
		}
	}

	public void setPath(String[] path) {
		if (path == null) {
			m_path = new String[0];
		} else {
			m_path = Arrays.copyOf(path, path.length);
		}
	}

	@Override
	public void validate(ActionContext<?> ctx) {
		if (m_action == null) {
			m_action = Action.XML;
		}
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/business/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.business;

public enum Action implements org.unidal.web.mvc.Action {
	LIST("list"),

	ADD("add"),

	AddSubmit("addSubmit"),

	DELETE("delete"),

	TagConfig("tagConfig"),

	AlertRuleAdd("alertRuleAdd"),

	AlertRuleAddSubmit("alertRuleAddSubmit"),

	CustomAdd("customAdd"),

	CustomAddSubmit("customAddSubmit"),

	CustomDelete("customDelete");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/config/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.config;

public enum Action implements org.unidal.web.mvc.Action {
	PROJECT_ALL("projects"),

	PROJECT_ADD("projectAdd"),

	PROJECT_UPDATE_SUBMIT("updateSubmit"),

	PROJECT_DELETE("projectDelete"),

	TOPOLOGY_GRAPH_NODE_CONFIG_LIST("topologyGraphNodeConfigList"),

	TOPOLOGY_GRAPH_NODE_CONFIG_ADD_OR_UPDATE("topologyGraphNodeConfigAdd"),

	TOPOLOGY_GRAPH_NODE_CONFIG_ADD_OR_UPDATE_SUBMIT("topologyGraphNodeConfigAddSumbit"),

	TOPOLOGY_GRAPH_NODE_CONFIG_DELETE("topologyGraphNodeConfigDelete"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_ADD_OR_UPDATE("topologyGraphEdgeConfigAdd"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_ADD_OR_UPDATE_SUBMIT("topologyGraphEdgeConfigAddSumbit"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_DELETE("topologyGraphEdgeConfigDelete"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_LIST("topologyGraphEdgeConfigList"),

	TOPO_GRAPH_FORMAT_CONFIG_UPDATE("topoGraphFormatUpdate"),

	HEARTBEAT_RULE_CONFIG_LIST("heartbeatRuleConfigList"),

	HEARTBEAT_RULE_ADD_OR_UPDATE("heartbeatRuleUpdate"),

	HEARTBEAT_RULE_ADD_OR_UPDATE_SUBMIT("heartbeatRuleSubmit"),

	HEARTBEAT_RULE_DELETE("heartbeatRulDelete"),

	ALERT_DEFAULT_RECEIVERS("alertDefaultReceivers"),

	ALERT_POLICY("alertPolicy"),

	HEARTBEAT_DISPLAY_POLICY("displayPolicy"),

	EXCEPTION("exception"),

	EXCEPTION_THRESHOLD_UPDATE("exceptionThresholdUpdate"),

	EXCEPTION_THRESHOLD_ADD("exceptionThresholdAdd"),

	EXCEPTION_THRESHOLD_UPDATE_SUBMIT("exceptionThresholdUpdateSubmit"),

	EXCEPTION_THRESHOLD_DELETE("exceptionThresholdDelete"),

	EXCEPTION_EXCLUDE_ADD("exceptionExcludeAdd"),

	EXCEPTION_EXCLUDE_UPDATE_SUBMIT("exceptionExcludeUpdateSubmit"),

	EXCEPTION_EXCLUDE_DELETE("exceptionExcludeDelete"),

	TRANSACTION_RULE("transactionRule"),

	TRANSACTION_RULE_ADD_OR_UPDATE("transactionRuleUpdate"),

	TRANSACTION_RULE_ADD_OR_UPDATE_SUBMIT("transactionRuleSubmit"),

	TRANSACTION_RULE_DELETE("transactionRuleDelete"),

	EVENT_RULE("eventRule"),

	EVENT_RULE_ADD_OR_UPDATE("eventRuleUpdate"),

	EVENT_RULE_ADD_OR_UPDATE_SUBMIT("eventRuleSubmit"),

	EVENT_RULE_DELETE("eventRuleDelete"),

	STORAGE_RULE("storageRule"),

	STORAGE_RULE_ADD_OR_UPDATE("storageRuleUpdate"),

	STORAGE_RULE_ADD_OR_UPDATE_SUBMIT("storageRuleSubmit"),

	STORAGE_RULE_DELETE("storageRuleDelete"),

	STORAGE_GROUP_CONFIG_UPDATE("storageGroupConfigUpdate"),

	DOMAIN_GROUP_CONFIGS("domainGroupConfigs"),

	DOMAIN_GROUP_CONFIG_UPDATE("domainGroupConfigUpdate"),

	DOMAIN_GROUP_CONFIG_SUBMIT("domainGroupConfigSubmit"),

	DOMAIN_GROUP_CONFIG_DELETE("domainGroupConfigDelete"),

	ROUTER_CONFIG_UPDATE("routerConfigUpdate"),

	SAMPLE_CONFIG_UPDATE("sampleConfigUpdate"),

	ALERT_SENDER_CONFIG_UPDATE("alertSenderConfigUpdate"),

	SERVER_FILTER_CONFIG_UPDATE("serverFilterConfigUpdate"),

	SERVER_CONFIG_UPDATE("serverConfigUpdate"),

	REPORT_RELOAD_CONFIG_UPDATE("reportReloadConfigUpdate"),

	ALL_REPORT_CONFIG("allReportConfig");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/login/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.login;

public enum Action implements org.unidal.web.mvc.Action {
	LOGIN("login"),

	LOGOUT("logout");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/login/LoginAction.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.login;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Retention(RUNTIME)
@Target(METHOD)
public @interface LoginAction {
	String[] includes() default {};

	String[] excludes() default {};
}

cat-home/src/main/java/com/dianping/cat/system/page/permission/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.permission;

public enum Action implements org.unidal.web.mvc.Action {
	USER("user"),

	RESOURCE("resource"),

	ERROR("error");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/plugin/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.plugin;

public enum Action implements org.unidal.web.mvc.Action {
	VIEW("view"),

	DOCFILE("doc");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/project/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.project;

public enum Action implements org.unidal.web.mvc.Action {
	DOMAINS("domains"),

	PROJECT_UPDATE("projectUpdate");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/router/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.router;

public enum Action implements org.unidal.web.mvc.Action {
	API("api"),

	JSON("json"),

	XML("xml"),

	BUILD("build"),

	MODEL("model");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/webapp/jsp/system/topology/topoGraphFormatConfig.jsp
<%@ page contentType="text/html; charset=utf-8"%>
<%@ taglib prefix="a" uri="/WEB-INF/app.tld"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="res" uri="http://www.unidal.org/webres"%>
<%@ taglib prefix="w" uri="http://www.unidal.org/web/core"%>

<a:config>
	<res:useJs value="${res.js.local['jquery.validate.min.js']}" target="head-js" />
	<res:useJs value="${res.js.local['editor.js']}" target="head-js" />
	<script src='${model.webapp}/assets/js/editor/ace.js'></script>
			<form name="topoGraphFormat" id="form" method="post" action="${model.pageUri}?op=topoGraphFormatUpdate" 
				onsubmit="return validate_form(this)">
				<table class="table table-striped table-condensed   table-hover">
					<tr><td>
					<input id="content" name="content" value="" type="hidden"/>
					<div id="editor" class="editor">${model.content}</div>
					</td></tr>
					<tr>
						<td style="text-align: center"><input class='btn btn-primary'
							type="submit" name="submit" id="submit" value="提交" /></td>
					</tr>
				</table>
					<h4 class="text-center text-danger" id="state">&nbsp;</h4>
			</form>
</a:config>
<script type="text/javascript">
	$(document).ready(function() {
		$('#application_config').addClass('active open');
		$('#topoGraphFormatUpdate').addClass('active');
		var state = '${model.opState}';
		if (state == 'Success') {
			$('#state').html('操作成功');
		} else {
			$('#state').html('操作失败');
		}
		setInterval(function() {
			$('#state').html('&nbsp;');
		}, 3000);
	});
</script>

cat-home/src/main/webapp/jsp/system/topology/topologyGraphNodeConfigAdd.jsp
<%@ page contentType="text/html; charset=utf-8" %>
<%@ taglib prefix="a" uri="/WEB-INF/app.tld"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="res" uri="http://www.unidal.org/webres"%>
<%@ taglib prefix="w" uri="http://www.unidal.org/web/core"%>

<jsp:useBean id="ctx" type="com.dianping.cat.system.page.config.Context" scope="request"/>
<jsp:useBean id="payload" type="com.dianping.cat.system.page.config.Payload" scope="request"/>
<jsp:useBean id="model" type="com.dianping.cat.system.page.config.Model" scope="request"/>

<a:config>
	<res:useJs value="${res.js.local['jquery.validate.min.js']}" target="head-js" />
	<res:useJs value="${res.js.local['dependencyConfig.js']}" target="head-js" />
	<res:useJs value="${res.js.local['alarm_js']}" target="head-js" />
	<res:useCss value="${res.css.local['select2.css']}" target="head-css" />
	<res:useJs value="${res.js.local['select2.min.js']}" target="head-js" />
	<script type="text/javascript">
		$(document).ready(function() {
			$('#application_config').addClass('active open');
			$('#topologyGraphNodeConfigList').addClass('active');
			
			var action = '${payload.action.name}';
			if(action=='topologyGraphNodeConfigDelete'||action=='topologyGraphNodeConfigAddSumbit'){
				var state = '${model.opState}';
				if(state=='Success'){
					$('#state').html('操作成功');
				}else{
					$('#state').html('操作失败');
				}
				setInterval(function(){
					$('#state').html('&nbsp;');
				},3000);
			}
		});
	</script>
<form name="topologyGraphNodeConfigAddSumbit" id="form" method="post" action="${model.pageUri}?op=topologyGraphNodeConfigAddSumbit">
	<h4 class="text-center text-danger" id="state">&nbsp;</h4>
	<h4 class="text-center text-danger">修改拓扑节点配置信息</h4>
	<table class="table table-striped table-condensed  ">
		<tr>
			<td width="40%"  style="text-align:right" class="text-success">节点规则类型</td>
			<td><input id="type" name="type" value="${payload.type}" readonly/></td>
		</tr>
		<tr>
			<td style="text-align:right" class="text-success">项目名称</td>
			<td>
				<c:if test="${not empty payload.domain}">
					<input id="id" name="domainConfig.id" value="${payload.domain}" readonly required/>
				</c:if>
				<c:if test="${empty payload.domain}">
					<select style="width:200px;" name="domainConfig.id" id="id">
	                     <c:forEach var="item" items="${model.projects}">
	                           <option value="${item.domain}">${item.domain}</option>
	                     </c:forEach>
                 	 </select>
				</c:if>
			</td>
		</tr>
		<tr>
			<td style="text-align:right" class="text-success">最少访问次数</td>
			<td><input id="warningThreshold" name="domainConfig.minCountThreshold" value="${model.domainConfig.minCountThreshold}" required/></td>
		</tr>
		<tr>
			<td style="text-align:right" class="text-success">一分钟异常数warning阈值</td>
			<td><input id="warningThreshold" name="domainConfig.warningThreshold" value="${model.domainConfig.warningThreshold}" required/></td>
		</tr>
		<tr>
			<td style="text-align:right" class="text-success">一分钟异常数error阈值</td>
			<td><input id="errorThreshold" name="domainConfig.errorThreshold" value="${model.domainConfig.errorThreshold}" required/></td>
		</tr>
		<c:if test="${payload.type ne 'Exception' }">
			<tr>
				<td style="text-align:right" class="text-success">响应时间warning阈值</td>
				<td><input id="warningResponseTime"  name="domainConfig.warningResponseTime" value="${model.domainConfig.warningResponseTime}" required/></td>
			</tr>
			<tr>
				<td style="text-align:right" class="text-success">响应时间error阈值</td>
				<td><input id="errorResponseTime"  name="domainConfig.errorResponseTime" value="${model.domainConfig.errorResponseTime}" required/></td>
			</tr>
		</c:if>
		<c:if test="${payload.type eq 'Exception' }">
			<tr style="display:none">
				<td style="text-align:right" class="text-success">响应时间warning阈值</td>
				<td><input id="warningResponseTime"  name="domainConfig.warningResponseTime" value="100" required/></td>
			</tr>
			<tr style="display:none">
				<td style="text-align:right" class="text-success">响应时间error阈值</td>
				<td><input id="errorResponseTime"  name="domainConfig.errorResponseTime" value="100" required/></td>
			</tr>
		</c:if>
		<tr>
			<td>&nbsp;</td>
			<td><input class='btn btn-primary btn-sm' id="addOrUpdateNodeSubmit" type="submit" name="submit" value="提交" /></td>
		</tr>
	</table>
</form>
</a:config>

cat-home/src/main/webapp/jsp/system/topology/topologyGraphOpState.jsp
<%@ page contentType="text/html; charset=utf-8" %>
<jsp:useBean id="model" type="com.dianping.cat.system.page.config.Model" scope="request"/>
${model.opState}